terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
    }
  }
}

resource "null_resource" "web_content" {
  triggers = {
    always_run = "${timestamp()}"  # Executa em cada `terraform apply`
  }

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = file("~/.ssh/id_ed25519")
    host        = aws_instance.unifor_ubuntu[0].public_ip
  }

  provisioner "remote-exec" {
    inline = [
      "echo 'server { listen 80; server_name localhost; location / { root /var/www/html; index index.html; } }' | sudo tee /etc/nginx/sites-available/default",
      "sudo mkdir -p /var/www/html",
    ]
  }

  provisioner "file" {
    content = <<-EOT
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Meu Servidor AWS</title>
          <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background-color: #f0f2f5; }
              .container { max-width: 800px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); }
              h1 { color: #1a73e8; text-align: center; }
              .info-section { margin-top: 20px; padding: 15px; background-color: #f8f9fa; border-radius: 4px; }
              .server-time { text-align: center; color: #666; font-style: italic; }
          </style>
      </head>
      <body>
          <div class="container">
              <h1>Bem vindo</h1>
              <div class="info-section">
                  <h2>Felipe Neres Ribeiro | Matrícula: 2327959</h2>
              </div>
              <div class="info-section">
                  <h2>Informações</h2>
                  <ul>
                      <li>Server: Nginx on Ubuntu</li>
                      <li>Instance Type: t2.micro</li>
                      <li>Region: us-east-1</li>
                  </ul>
              </div>
              <div class="info-section">
                  <h2>Sobre</h2>
                  <p>Página gerada para apresentação do Felipe na disciplina de Infraestrutura Automatizada</p>
              </div>
              <p class="server-time">Page generated by Terraform deployment</p>
          </div>
      </body>
      </html>
    EOT
    destination = "/tmp/index.html"
  }

  # Terceiro provisionamento: Move o arquivo para a pasta correta e reinicia o Nginx
  provisioner "remote-exec" {
    inline = [
      "sudo mv /tmp/index.html /var/www/html/index.html",
      "sudo systemctl restart nginx"
    ]
  }
}
